### ISSUE TITLE
Doesn't Appear to Be Working in NeoVim on OSX Sierra

### ISSUE THREAD

**Issue by jlmcgehee21** [stevearc/vim-arduino#6]
I am trying to get this running, but am not having much success.  If I type `:help arduino` within neovim, I _do_ get the help docs, but no `:Arduino*` commands seem to be working.

In the [Arduino CLI](https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc) docs, it states:
> Note that on MacOS X, the main executable is Arduino.app/Contents/MacOS/Arduino instead of arduino.

Perhaps this is the problem? I tried aliasing the above path to `arduino` to no avail, and setting
```
let g:arduino_cmd = '/Applications/Arduino.app/Contents/MacOS/Arduino'
let g:arduino_dir = '/Applications/Arduino.app/Contents/MacOS/'
```
in my `init.vim` yielded no results as well.

**Comment by stevearc** [comment]
Try updating to commit https://github.com/stevearc/vim-arduino/commit/e76ccf968ba23f6c860c28cb8114f36b6a13e8ce and see if that works. I just added some better support for Mac. Note that due to some unfortunate limitations, running the arduino commands on a mac will bring up the splash screen. See https://github.com/arduino/Arduino/issues/1970
